### ISSUE TITLE
Setup Identity and User group management correctly

### ISSUE THREAD

**Issue by jonasanker** [AnalogIO/analog-core#33]
We depend on admin tokens and do not use User Groups according to ASP.NET best practices.

**Comment by TTA777** [comment]
For adding the check for a specific role to an endpoint see [here](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/roles?view=aspnetcore-5.0).  Since we are issuing the tokens ourselves, and most of the official documentation does not assume that you do this, I can't remember where the docs for adding the roles to the actual claims are. You can take a look at how I have done it in the [shiftplanning API](https://github.com/AnalogIO/ShiftPlanning_API/blob/feature/dotnet5Migration/API/ShiftPlanning.WebApi/Token/TokenManager.cs) for inspiration. Note that in shiftplanning we allow for a user to have multiple roles, so we would be able to do it slightly simpler here in the coffeecardAPI

**Comment by TTA777** [comment]
Implemented
